### ISSUE TITLE
Package conflicts in requirements.txt

### ISSUE THREAD

**Issue by ETAOIK** [zjunlp/ContinueMKGC#3]
Dear authors, 

Hi! I am encountering some difficulties while creating an environment for the MSPT model. I am confused by the requirements.txt file that faiss==1.5.3 in PyPI only supports Python versions equal to or lower than 3.7 (py 2.7/3.5/3.6/3.7), while scikit_learn==1.2.0 in PyPI only supports Python versions equal to or higher than 3.8 (py3.8/3.9/3.10/3.11). It appears that these two packages conflict with each other. 

Could you kindly tell me on how to address this issue? Any assistance you can provide would be greatly appreciated. Thank you very much!

Shaunak

**Comment by njcx-ai** [comment]
Thank you for your interest in our paper. We apologize for the potential conflict between the two packages mentioned here. You can try installing them together to see if it works. Alternatively, a more reliable solution would be to downgrade the version of scikit_learn to avoid compatibility issues.

**Comment by wanglu1214** [comment]
> 亲爱的作者们，
> 
> 你好！我在为 MSPT 模型创建环境时遇到了一些困难。我对 requests.txt 文件感到困惑，PyPI 中的 faiss==1.5.3 只支持等于或低于 3.7 的 Python 版本（py 2.7/3.5/3.6） /3.7），而 PyPI 中的 scikit_learn==1.2.0 仅支持相当于或等于 3.8 的 Python 版本（py3.8/3.9/3.10/3.11）。这两个包似乎相互冲突。
> 
> 您能告诉我如何解决这个问题吗？如果您能提供任何帮助，我将不胜感激。非常感谢！
> 
> 沙奈克

你好，请问这个问题你解决了吗？如果解决了可以告诉我你是怎么解决的吗？非常感谢

**Comment by njcx-ai** [comment]
您好，非常感谢您对我们工作的关注，建议您将scikit_learn的版本适当降低试试呢。

**Comment by zxlzr** [comment]
请问您的问题解决了吗？

**Comment by ETAOIK** [comment]
@zxlzr @wanglu1214 My problem is solved and the results of MSPT were wonderfully reproduced, the dependencies of my reproduced env are python==3.7.0 and scikit-learn==1.0.2. 
@njcx-ai Thanks a lot for your kind help, really appreciated! And this issue could be closed.

**Comment by njcx-ai** [comment]
Thank you once again for your attention and feedback.
