### ISSUE TITLE
VERSION

### ISSUE THREAD

**Issue by Benidcum** [zjunlp/ContinueMKGC#4]
What is the version of Python?plz,thank you.

**Comment by njcx-ai** [comment]
Hello, thank you for your interest in our work. Please note that the version of Python should be 3.7 or 3.8.

**Comment by Benidcum** [comment]
> Hello, thank you for your interest in our work. Please note that the version of Python should be 3.7 or 3.8.

Thank you very much for your reply!It will be very helpful to me.

**Comment by libin99527** [comment]
No module named 'models.modeling_unimo_mike'
