### ISSUE TITLE
请问一下为什么没有MNER数据集？

### ISSUE THREAD

**Issue by 19660930** [zjunlp/ContinueMKGC#6]
能不能提供一下具体的数据集呢，谢谢

**Comment by njcx-ai** [comment]
您好，非常感谢您对我们工作的关注。MNER数据集是在MNER/data 目录下哈

**Comment by 19660930** [comment]
你好，我下载之后看到了MNER下的data中并没有向您描述的文件树中的Twitter系列数据集，仅有sep系列的数据，并没有类似于twitter2017_images等数据，不知道是否遗漏了？

**Comment by njcx-ai** [comment]
You can download the twitter2017 dataset via this [link](https://drive.google.com/file/d/1ogfbn-XEYtk9GpUECq1-IwzINnhKGJqy/view?usp=sharing). Please merge the folder MNER/data/twitter2017 we provided with the extracted folder. The merged file tree can refer to section 1.1.

**Comment by 19660930** [comment]
好的，我已经了解了，非常感谢您的回答
